"use client";

import { trpc } from "@/lib/trpc";
import { AlertTriangle, CheckCircle2, Database, Loader2, RefreshCw, UploadCloud, Wrench } from "lucide-react";

export function DatabaseStatusBanner() {
  const status = trpc.database.status.useQuery(undefined, { retry: false });
  const portfolio = trpc.portfolio.list.useQuery(undefined, { enabled: status.data?.schemaReady === true, retry: false });
  const initialize = trpc.database.initialize.useMutation({ onSuccess: () => status.refetch() });
  const seedPortfolio = trpc.database.seedPortfolio.useMutation({ onSuccess: () => portfolio.refetch() });

  if (status.isLoading) return <div className="mb-6 flex items-center gap-2 rounded-2xl border border-slate-200 bg-white px-4 py-3 text-sm text-slate-500"><Loader2 className="h-4 w-4 animate-spin" /> جارٍ فحص اتصال البيانات...</div>;
  if (!status.data?.schemaReady) return <div className="mb-6 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-950"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="mt-0.5 grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-amber-100 text-amber-700"><Database className="h-4 w-4" /></div><div><p className="font-bold">قاعدة البيانات متصلة لكنها تحتاج تهيئة الجداول.</p><p className="mt-1 text-sm leading-6 text-amber-800">يمكن للمدير تشغيل تهيئة آمنة من هنا. لن تُحذف البيانات الموجودة.</p></div></div><button type="button" disabled={initialize.isPending || status.data?.connected === false} onClick={() => initialize.mutate()} className="button-primary shrink-0"><Wrench className="h-4 w-4" /> {initialize.isPending ? "جارٍ التهيئة..." : "تهيئة قاعدة البيانات"}</button></div>{initialize.error && <p className="mt-3 flex items-center gap-2 text-sm font-semibold text-red-700"><AlertTriangle className="h-4 w-4" /> تعذر التهيئة. تحقق من متغير اتصال PostgreSQL في Vercel.</p>}</div>;
  if (portfolio.isLoading) return <div className="mb-6 flex items-center gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800"><CheckCircle2 className="h-4 w-4" /> قاعدة البيانات متصلة، جارٍ فحص ربط الأعمال...</div>;
  if (portfolio.isError) return <div className="mb-6 flex items-center gap-2 rounded-2xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-800"><AlertTriangle className="h-4 w-4" /> الاتصال جاهز، لكن تعذر قراءة جدول الأعمال. <button type="button" onClick={() => portfolio.refetch()} className="mr-auto inline-flex items-center gap-1 underline"><RefreshCw className="h-3.5 w-3.5" /> إعادة المحاولة</button></div>;
  if (portfolio.data?.length === 0) return <div className="mb-6 rounded-2xl border border-indigo-200 bg-indigo-50 p-4 text-indigo-950"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-start gap-3"><div className="mt-0.5 grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-indigo-100 text-indigo-700"><UploadCloud className="h-4 w-4" /></div><div><p className="font-bold">قاعدة البيانات جاهزة، لكن الأعمال الثلاثة لم تُزامن بعد.</p><p className="mt-1 text-sm leading-6 text-indigo-800">سيتم نقل السجلات الموثقة الموجودة في الكتالوج إلى لوحة الإدارة دون تكرار.</p></div></div><button type="button" disabled={seedPortfolio.isPending} onClick={() => seedPortfolio.mutate()} className="button-primary shrink-0"><UploadCloud className="h-4 w-4" /> {seedPortfolio.isPending ? "جارٍ المزامنة..." : "مزامنة المشاريع الثلاثة"}</button></div>{seedPortfolio.error && <p className="mt-3 text-sm font-semibold text-red-700">تعذرت المزامنة. أعد المحاولة بعد التحقق من اتصال قاعدة البيانات.</p>}</div>;
  return <div className="mb-6 flex items-center gap-2 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800"><CheckCircle2 className="h-4 w-4" /> قاعدة البيانات متصلة، وجداول الإدارة والأعمال جاهزة.</div>;
}
