"use client";

import { useState } from "react";
import DashboardLayout from "@/components/DashboardLayout";
import { trpc } from "@/lib/trpc";
import { Archive, BriefcaseBusiness, Check, Eye, Plus, Save } from "lucide-react";
import { AdminEmptyState, AdminErrorState, AdminLoadingState } from "@/components/AdminQueryState";
import { AdminPageHeader } from "@/components/AdminPageHeader";

const emptyForm = { slug: "", title: "", excerpt: "", body: "", category: "", service: "", clientName: "", status: "draft" as const };

function PortfolioAdmin() {
  const utils = trpc.useUtils();
  const items = trpc.portfolio.list.useQuery();
  const [form, setForm] = useState(emptyForm);
  const [isOpen, setIsOpen] = useState(false);
  const create = trpc.portfolio.create.useMutation({ onSuccess: async () => { await utils.portfolio.list.invalidate(); setForm(emptyForm); setIsOpen(false); } });
  const update = trpc.portfolio.update.useMutation({ onSuccess: () => utils.portfolio.list.invalidate() });

  return <div dir="rtl" className="mx-auto max-w-7xl space-y-7">
    <AdminPageHeader eyebrow="ORA / PORTFOLIO" title="الأعمال ودراسات الحالات" description="أدر المشاريع المنشورة، راجع المسودات، واحفظ توثيقًا واضحًا لكل عميل." action={<button type="button" onClick={() => setIsOpen(value => !value)} className="button-primary"><Plus className="h-4 w-4" /> دراسة حالة جديدة</button>} />
    {isOpen && <form onSubmit={event => { event.preventDefault(); create.mutate({ ...form, clientConsent: false, featured: false, mediaUrls: [], deliverables: [], results: [], techStack: [], displayOrder: 0 }); }} className="rounded-[1.5rem] border border-indigo-100 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="font-display text-2xl font-bold text-slate-900">إضافة مسودة</h2><button type="button" onClick={() => setIsOpen(false)} className="text-sm text-slate-500">إغلاق</button></div><div className="mt-6 grid gap-4 md:grid-cols-2"><label className="field-label">العنوان<input className="field-input mt-2" required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></label><label className="field-label">الرابط المختصر<input className="field-input mt-2" required dir="ltr" placeholder="product-discovery" value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value })} /></label><label className="field-label">الخدمة<input className="field-input mt-2" value={form.service} onChange={e => setForm({ ...form, service: e.target.value })} /></label><label className="field-label">القطاع<input className="field-input mt-2" value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} /></label><label className="field-label md:col-span-2">الملخص<textarea className="field-input mt-2 min-h-24" required value={form.excerpt} onChange={e => setForm({ ...form, excerpt: e.target.value })} /></label><label className="field-label md:col-span-2">محتوى دراسة الحالة<textarea className="field-input mt-2 min-h-48" required value={form.body} onChange={e => setForm({ ...form, body: e.target.value })} /></label></div><div className="mt-6 flex items-center gap-3"><button disabled={create.isPending} className="button-primary"><Save className="h-4 w-4" /> {create.isPending ? "جارٍ الحفظ..." : "حفظ المسودة"}</button>{create.error && <p className="text-sm text-red-600">تعذر الحفظ. تحقق من البيانات والاتصال.</p>}</div></form>}
    <div className="grid gap-4">{items.isLoading ? <AdminLoadingState label="جارٍ تحميل دراسات الحالة..." /> : items.isError ? <AdminErrorState label="تعذر تحميل دراسات الحالة" onRetry={() => items.refetch()} /> : items.data?.length ? items.data.map(item => <article key={item.id} className="rounded-[1.5rem] border border-slate-200 bg-white p-6 shadow-sm"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-start"><div className="flex gap-4"><div className="grid h-12 w-12 shrink-0 place-items-center rounded-2xl bg-indigo-50 text-indigo-600"><BriefcaseBusiness className="h-5 w-5" /></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-display text-2xl font-bold text-slate-900">{item.title}</h2><span className={`rounded-full px-3 py-1 text-xs font-bold ${item.status === "published" ? "bg-emerald-50 text-emerald-700" : item.status === "archived" ? "bg-slate-100 text-slate-500" : "bg-amber-50 text-amber-700"}`}>{item.status === "published" ? "منشور" : item.status === "archived" ? "مؤرشف" : "مسودة"}</span></div><p className="mt-2 max-w-3xl text-sm leading-7 text-slate-500">{item.excerpt}</p><p className="mt-2 text-xs text-slate-400" dir="ltr">/work/{item.slug}</p></div></div><div className="flex flex-wrap gap-2"><a href={`/work/${item.slug}`} target="_blank" rel="noreferrer" className="button-secondary"><Eye className="h-4 w-4" /> معاينة</a>{item.status !== "published" && <button type="button" onClick={() => update.mutate({ id: item.id, values: { status: "published", clientConsent: true } })} className="button-primary"><Check className="h-4 w-4" /> نشر</button>}{item.status === "published" && <button type="button" onClick={() => update.mutate({ id: item.id, values: { status: "archived" } })} className="button-secondary"><Archive className="h-4 w-4" /> أرشفة</button>}</div></div></article>) : <AdminEmptyState icon={BriefcaseBusiness} title="لا توجد دراسات حالة في قاعدة البيانات" description="يمكنك إضافة أول مسودة بعد تهيئة جداول PostgreSQL، ثم مراجعتها ونشرها من هنا." />}</div>
  </div>;
}

export default function PortfolioAdminPage() { return <DashboardLayout><PortfolioAdmin /></DashboardLayout>; }
